### ISSUE TITLE
Terminology Standardization

### ISSUE THREAD

**Issue by BennyOptions** [icon-project/btp-product#19]
Eric and Cyrus are working on creating more recognizable based on industry standards for BTP

**Comment by han-so1omon** [comment]
@BennyOptions Please follow along with this glossary:

[v1](https://docs.google.com/document/d/1NA-UjwqzecN5EmVT9Er1sDty2k29KOmpfB0xZZ3YywA/edit?usp=sharing) - old terminology
[v2](https://docs.google.com/document/d/10MNHLWf4sF9Qi-vcebAQh6u6GDM2FN4waJGgR4eJgp0/edit?usp=sharing) - new terminology. includes old terminology to support existing documentation and articles
