### ISSUE TITLE
BTP Whitepaper

### ISSUE THREAD

**Issue by BennyOptions** [icon-project/btp-product#36]
It doesn't need to be long. It should be mostly technical, focused on how BTP messages work, how it's secured, the role of the Relay, the role of each contract, how each contract actually works (i.e. how blockUpdate is performed).

**Comment by BennyOptions** [comment]
Initial thoughts on structure:

- Introduction (include brief explanation on security)
- Components
  - BMR
  - BMV
  - BMC
  - BSH
  - Full integration explanation of all components
- Arbitrary Call Service
- Conclusion

**Comment by hong-icon** [comment]
https://docs.google.com/document/d/1ZkcAYAWrTUql_rmd3Hjg7rlnp0PG-Eamtc03BD0KqXY/edit
