### ISSUE TITLE
xCall Fee Structure

### ISSUE THREAD

**Issue by BennyOptions** [icon-project/btp-product#46]
Let's add another value in the database for each entry. We need two types of fees, one for the BTP protocol and one to compensate Relays for the cost of processing the message. It can be very simple for now, but want the data structure to be there from the start. For example:

feeObject:
Dest Chain = Harmony
relayFee = .25 ICX
protocolFee = 0.01ICX

Relay fee goes to Relay, protocol fee goes to BTP protocol (eventually, Fee Aggregator SCORE)

For now, we don't need actual destinations of these fees. Just an admin function like setRelayFeeAddress and setProtocolFeeAddress.

**Comment by sink772** [comment]
Added in https://github.com/icon-project/btp/commit/bf71b0a90a10cc86695907d19106476a454e4b29
