### ISSUE TITLE
BTP Benefits Doc

### ISSUE THREAD

**Issue by BennyOptions** [icon-project/btp-product#8]
- [BTP Benefits](https://docs.google.com/document/d/1gbA66UiY707wK8WhZhIsvjwy7sFp5vNAyGmAK18Ej9U/edit#heading=h.bv7oyf27619)

**Comment by hong-icon** [comment]
one-pager

**Comment by hong-icon** [comment]
- [BTP Benefits](https://docs.google.com/document/d/1gbA66UiY707wK8WhZhIsvjwy7sFp5vNAyGmAK18Ej9U/edit)

**Comment by hong-icon** [comment]
- [BTP Benefits](https://docs.google.com/document/d/1gbA66UiY707wK8WhZhIsvjwy7sFp5vNAyGmAK18Ej9U/edit#heading=h.bv7oyf27619)

**Comment by han-so1omon** [comment]
@BennyOptions @hong-icon Please track this document in the [Notion page for BTP alternatives](https://www.notion.so/iconfoundation/BTP-Alternatives-Competition-595e57e07efa48908cc89494a6ef290c) as well
